### ISSUE TITLE
2.1.1 on OpenShift?

### ISSUE THREAD

**Issue by sweetticket** [NYUCCL/psiTurk#147]
Is there a way to install version 2.1.1 on Openshift? All I have is this link from the 2.0 docs: git+git://github.com/NYUCCL/psiTurk.git@dev

EDIT:
Nevermind, I got it. but I have a new issue now. I just upgraded from 2.0.1 to 2.1.1 on OpenShift and now it gives me this error every time I try to turn on the server. Is there a way I downgrade to 2.0.1?

Traceback (most recent call last):
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/cmd2.py", line 783, in onecmd_plus_hooks
    stop = self.postcmd(stop, statement)
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 205, in postcmd
    self.color_prompt()
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 571, in color_prompt
    server_status = self.server.is_server_running()
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psiturk/experiment_server_controller.py", line 144, in is_server_running
    psiturk_exp_ports = [process[0].laddr[1] for process in [psutil.Process(int(pid)).get_connections() for pid in output]]
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psutil/_common.py", line 144, in inner
    return getattr(self, replacement)(_args, *_kwargs)
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psutil/__init__.py", line 963, in connections
    return self._proc.connections(kind)
  File "/var/lib/openshift/53d9c3855973ca578a0003ee/python/virtenv/lib/python2.7/site-packages/psutil/_pslinux.py", line 706, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: (pid=361397)
(pid=361397)

**Comment by bernuly** [comment]
Just installed psiturk on openshift following the instructions on http://psiturk.readthedocs.org/en/latest/openshift.html
and get very similar error messages:
Traceback (most recent call last):
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/cmd2.py", line 789, in onecmd_plus_hooks
    stop = self.postcmd(stop, statement)
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 205, in postcmd
    self.color_prompt()
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 571, in color_prompt
    server_status = self.server.is_server_running()
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psiturk/experiment_server_controller.py", line 144, in is_server_running
    psiturk_exp_ports = [process[0].laddr[1] for process in [psutil.Process(int(pid)).get_connections() for pid in output]]
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psutil/_common.py", line 143, in inner
    return getattr(self, replacement)(*args, **kwargs)
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psutil/__init__.py", line 983, in connections
    return self._proc.connections(kind)
  File "/var/lib/openshift/5558239d4382eca5830000a9/python/virtenv/lib/python2.7/site-packages/psutil/_pslinux.py", line 656, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: (pid=422798)
(pid=422798)

**Comment by bernuly** [comment]
problem seems to be that Process.get_connections() requires root...
