### ISSUE TITLE
Directions for setting up Openshift no longer valid

### ISSUE THREAD

**Issue by bisraelsen** [NYUCCL/psiTurk#155]
The documentation for setting up psiturk on Openshift seem to be out of date.

These directions: [Old Documents readthedocs](http://psiturk.readthedocs.org/en/latest/install.html#installation-steps)
seem to be the same as: [Old Document on github](https://github.com/jbmartin/psiturk-on-openshift)

Which says it is deprecated and to look to this project instead.

I presume these are the most up-to-date instructions: [Up to date documents readthedocs](http://psiturk.readthedocs.org/en/latest/openshift.html)

However following these instructions yields the following error when trying to start the server:

``` bash
https://psiturk.org
 ______   ______     __     ______   __  __     ______     __  __    
/\  == \ /\  ___\   /\ \   /\__  _\ /\ \/\ \   /\  == \   /\ \/ /    
\ \  _-/ \ \___  \  \ \ \  \/_/\ \/ \ \ \_\ \  \ \  __<   \ \  _"-.  
 \ \_\    \/\_____\  \ \_\    \ \_\  \ \_____\  \ \_\ \_\  \ \_\ \_\ 
  \/_/     \/_____/   \/_/     \/_/   \/_____/   \/_/ /_/   \/_/\/_/ 

             an open platform for science on Amazon Mechanical Turk

--------------------------------------------------------------------
System status:

Hi all, You need to be running psiTurk version >= 2.0.0 to use the 
Ad Server feature!  

The latest stable version is 2.1.1.

Check https://github.com/NYUCCL/psiTurk or https://psiturk.org for 
latest info.
psiTurk version 2.1.1
Type "help" for more information.
[psiTurk server:off mode:sdbx #HITs:0]$ server on
Experiment server launching...
Now serving on bisraelsen-cubexp.rhcloud.com
Traceback (most recent call last):
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/cmd2.py", line 783, in onecmd_plus_hooks
    stop = self.postcmd(stop, statement)
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 205, in postcmd
    self.color_prompt()
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 571, in color_prompt
    server_status = self.server.is_server_running()
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psiturk/experiment_server_controller.py", line 144, in is_server_running
    psiturk_exp_ports = [process[0].laddr[1] for process in [psutil.Process(int(pid)).get_connections() for pid in output]]
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psutil/_common.py", line 144, in inner
    return getattr(self, replacement)(*args, **kwargs)
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psutil/__init__.py", line 963, in connections
    return self._proc.connections(kind)
  File "/var/lib/openshift/5464db04e0b8cdd6d50001a3/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/psutil/_pslinux.py", line 709, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: (pid=419451)
(pid=419451)
```

Running `ps aux` yields (I included because I am not sure what else may be important, however pid=419451is being used by gunicorn):

``` bash
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
4815     354841  0.0  0.0   9508   452 ?        S    Nov13   0:00 /bin/bash /var/lib/openshift/5464db04e0b8cdd6d50001a3/mysql/bin/cont
4815     354846  0.0  0.0   4072   460 ?        S    Nov13   0:00 /usr/bin/scl enable mysql55 /opt/rh/mysql55/root//usr/bin/mysqld_saf
4815     354848  0.0  0.0   9240   988 ?        S    Nov13   0:00 /bin/bash /var/tmp/sclM19aWF
4815     354851  0.0  0.0   9376  1028 ?        S    Nov13   0:00 /bin/sh /opt/rh/mysql55/root//usr/bin/mysqld_safe --defaults-file=/v
4815     354852  0.0  0.0 185752  4140 ?        Sl   Nov13   0:00 /usr/bin/logshifter -tag mysql
4815     355226  0.0  0.0 378628 10784 ?        Sl   Nov13   0:34 /opt/rh/mysql55/root/usr/libexec/mysqld --defaults-file=/var/lib/ope
4815     356174  0.0  0.0 429052 10700 ?        S    Nov13   0:01 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     356175  0.0  0.0 195996  2136 ?        Sl   Nov13   0:00 /usr/bin/logshifter -tag phpmyadmin
4815     356189  0.0  0.0   4076   436 ?        S    Nov13   0:00 tee
4815     356191  0.0  0.0   4076   428 ?        S    Nov13   0:00 tee
4815     356200  0.0  0.0 429052   452 ?        S    Nov13   0:00 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     359369  0.0  0.0 108060  2932 ?        S    Nov13   0:01 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     359370  0.0  0.0 120216  2136 ?        Sl   Nov13   0:00 /usr/bin/logshifter -tag python
4815     359379  0.0  0.0   4076   436 ?        S    Nov13   0:00 tee
4815     359382  0.0  0.0   4076   460 ?        S    Nov13   0:00 tee
4815     359383  0.0  0.0 378248  2924 ?        Sl   Nov13   0:01 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     359384  0.0  0.0 378248  2924 ?        Sl   Nov13   0:02 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     359385  0.0  0.0 109964  2632 ?        S    Nov13   0:00 /usr/sbin/httpd -C Include /var/lib/openshift/5464db04e0b8cdd6d50001
4815     412813  0.0  0.0 109252  2772 ?        S    11:00   0:00 sshd: 5464db04e0b8cdd6d50001a3@pts/1
4815     412818  0.0  0.0 106640  2264 pts/1    Ss   11:00   0:00 /bin/bash --init-file /usr/bin/rhcsh -i
4815     419451  0.0  0.0 209616 13220 pts/1    S    11:02   0:00 gunicorn: master [psiturk_experiment_server]                       
4815     419465  0.1  0.1 246268 25736 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419468  0.1  0.1 246280 25744 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419469  0.2  0.1 246288 25752 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419471  0.2  0.1 246292 25756 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419474  0.2  0.1 246308 25768 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419476  0.1  0.1 246320 25776 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419490  0.2  0.1 246328 25780 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419491  0.2  0.1 246344 25792 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     419492  0.1  0.1 246352 25796 pts/1    S    11:02   0:00 gunicorn: worker [psiturk_experiment_server]                       
4815     435557  0.0  0.0 108136  1084 pts/1    R+   11:06   0:00 ps aux
```

**Comment by zorro4** [comment]
I looked into this and it looks like the problem is that some systems have very restrictive security and don't allow the inspection of processes. Looks like OpenShift is now one of them. However, unless I'm mistaken, the current get_connections() line in experiment_server_controller.py is unnecessary, as the only test that depends on it checks if there are any processes matching psiturk, not anything specific to the ports that those processes use. 

I'm about request a pull in which I just deleted that line and instead used output (the list of PIDs that match psiturk). So far it seems to fix the problem for me (in the turk sandbox). Pretty sure it doesn't affect anything else but I could be wrong.

**Comment by korymath** [comment]
Thank you for the heads up and great error reporting on this, but I attempted to upgrade with your pull req... or pip install git+https://github.com/zorro4/psiTurk.git --upgrade and now I am getting a new error.

[psiTurk server:status unknown mode:sdbx #HITs:0]$ server on
Error: Not sure what to tell you...
