### ISSUE TITLE
download_datafiles fails when data is None

### ISSUE THREAD

**Issue by john-guerra** [NYUCCL/psiTurk#177]
```
[psiTurk server:on mode:sdbx #HITs:1]$ download_datafiles
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 788, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 871, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 366, in do_download_datafiles
    ret = "".join([contents[k](p) for p in query])
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 363, in <lambda>
    p.get_question_data()}
  File "/usr/local/lib/python2.7/dist-packages/psiturk/models.py", line 100, in get_question_data
    questiondata = json.loads(self.datastring)["questiondata"]
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
expected string or buffer
````

This fails because ```self.datastring``` is None

**Comment by john-guerra** [comment]
It seems like this #177 has already been fixed in the dev branch. Closing it
