### ISSUE TITLE
Not a directory boto error

### ISSUE THREAD

**Issue by twiecki** [NYUCCL/psiTurk#216]
Vanilla psiturk master installation with the example task:
```
>>psiturk
Traceback (most recent call last):
  File "/home/wiecki/miniconda3/envs/psiturk/bin/psiturk", line 9, in <module>
    load_entry_point('PsiTurk==2.1.2.dev0', 'console_scripts', 'psiturk')()
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/PsiTurk-2.1.2.dev0-py2.7.egg/psiturk/command_line.py", line 15, in process
    launch_shell()
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/PsiTurk-2.1.2.dev0-py2.7.egg/psiturk/command_line.py", line 105, in launch_shell
    ps.run(cabinmode=args.cabinmode)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/PsiTurk-2.1.2.dev0-py2.7.egg/psiturk/psiturk_shell.py", line 1817, in run
    config.getboolean('Shell Parameters', 'launch_in_sandbox_mode'))
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/PsiTurk-2.1.2.dev0-py2.7.egg/psiturk/amt_services.py", line 307, in __init__
    self.valid_login = self.verify_aws_login()
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/PsiTurk-2.1.2.dev0-py2.7.egg/psiturk/amt_services.py", line 497, in verify_aws_login
    self.mtc.get_account_balance()
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/boto-2.15.0-py2.7.egg/boto/mturk/connection.py", line 72, in get_account_balance
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/boto-2.15.0-py2.7.egg/boto/mturk/connection.py", line 820, in _process_request
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/boto-2.15.0-py2.7.egg/boto/connection.py", line 1049, in make_request
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/boto-2.15.0-py2.7.egg/boto/connection.py", line 887, in _mexe
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/site-packages/boto-2.15.0-py2.7.egg/boto/https_connection.py", line 117, in connect
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/home/wiecki/miniconda3/envs/psiturk/lib/python2.7/ssl.py", line 520, in __init__
    self._context.load_verify_locations(ca_certs)
IOError: [Errno 20] Not a directory
```

**Comment by deargle** [comment]
Kind of relevant: http://stackoverflow.com/a/36083226/5917194
Try `pip install ssl`?

**Comment by twiecki** [comment]
Thanks, after reinstalling it actually started working so I'm going to suspect it pulled in `ssl` at some point. Maybe add that to `setup.py`.
