### ISSUE TITLE
Quickstart guide not accurate

### ISSUE THREAD

**Issue by abendebury** [NYUCCL/psiTurk#247]
I attempted to follow the quickstart guide but I encountered some errors:

https://gist.github.com/PlasmaSheep/977c198b94b76a3e31a350abf9959efa

Error 1:

```
[2016-07-27 14:47:02,100] ERROR in experiment: /home/alyosha/.virtualenvs/psiturk/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
```

I'm not sure how to fix this or why it happens. I was unable to find any more detailed error than this.

Error 2:

```
Traceback (most recent call last):
  File "/home/alyosha/.virtualenvs/psiturk/lib/python2.7/site-packages/cmd2.py", line 789, in onecmd_plus_hooks
    stop = self.postcmd(stop, statement)
  File "/home/alyosha/.virtualenvs/psiturk/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 205, in postcmd
    self.color_prompt()
  File "/home/alyosha/.virtualenvs/psiturk/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 571, in color_prompt
    server_status = self.server.is_server_running()
  File "/home/alyosha/.virtualenvs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server_controller.py", line 144, in is_server_running
    psiturk_exp_ports = [process[0].laddr[1] for process in [psutil.Process(int(pid)).get_connections() for pid in output]]
AttributeError: 'Process' object has no attribute 'get_connections'
'Process' object has no attribute 'get_connections'
```

Googling around, I was able to solve this like so:

https://gist.github.com/PlasmaSheep/ca37c57b889e915a9a4afea73ca18eef

So it seems that you have the wrong version of psuitl required.

**Comment by Speldosa** [comment]
The gist links don't work anymore. Shouldn't this issue just be closed?
