### ISSUE TITLE
adding easy heroku deployment with ssl support

### ISSUE THREAD

**Issue by braingineer** [NYUCCL/psiTurk#254]
Hi all,

I've been poking around for some solutions to allow repeated workers.  #214 and #90 are the standing reference points.  @gureckis mentioned that the ad server might be fussy to get working with allowing repeated workers.  

In addition, though, #162 reports wanting a docker image to get things up and running. 

To wrap those together, I wanted to drop some bread crumbs. I'm hoping to get to this in mid-February, but I'm ok with anyone wanting to push on it before then.  Cog Sci deadline is February 1st and I'm currently working towards that. 

The bread crumbs:

- An automated certbot for deploying Let's Encrypt SSL certs to Heroku: [gboudreau/certbot-heroku](https://github.com/gboudreau/certbot-heroku)
- An example of a one-click deployment implementation: [rauchg/slackin](https://github.com/rauchg/slackin)
  - Specifically for this one, if you scroll down the repo's readme, there's a Heroku link. Clicking that deploys the implementation. 
- A docker-compose implementation with psiturk: [mvdoc/psiturk-docker](https://github.com/mvdoc/psiturk-docker)

**Comment by deargle** [comment]
Note to the reader, repeat workers as implemented in #214 will work as long as you're not using the ad server (just set `use_psiturk_ad_server = false` and point `ad_location` at heroku, see [here](https://psiturk.readthedocs.io/en/latest/config/shell_parameters.html#use-psiturk-ad-server-true-false) ). 

I could merge #214 if it is desired, even though it won't work with the ad-server yet.

**Comment by suchow** [comment]
@braingineer 

Regarding Heroku, the SSL certificate is unnecessary because all `*.herokuapp.com` subdomains are already SSL-enabled.

There are also some changes you'll need to make to psiTurk to get things running on Heroku. In particular, check out the seven most recent commits on https://github.com/suchow/psiTurk-heroku/commits/master. At the time I was testing that, I also created the following instructions, in case they're of any use:

```
Step 1. Create a Heroku account

Step 2. Install the Heroku toolbelt (https://toolbelt.heroku.com/)

Step 3. Install the custom version of psiTurk (https://github.com/suchow/psiTurk-heroku)

Step 4. Create a copy of the demo app (psiturk-setup-example).

Step 5. Initialize a Git repository inside the demo app (git init)

Step 6. Create a new app using the Heroku toolbelt (heroku create)

Step 7. Add a Postgres database to the Heroku app (heroku addons:create heroku-postgresql)

Step 8. Get the URL of the Postgres database that you have just created (heroku config:get DATABASE_URL)

Step 9. In the demo app, you should see a file config.txt. Replace the database_url (should start with postgresql://) with the URL that you retrieved in Step 8.

Step 10. Set an environment variable with the HOST name (heroku config:set HOST=xyz.herokuapp.com), where xyz is the app name that was printed in Step 6.

Step 11. Set environment variables for your psiTurk and MTurk, replacing XYZ with your access and secret keys:

	heroku config:set psiturk_access_key_id=XYZ
	heroku config:set psiturk_secret_access_id=XYZ
	heroku config:set aws_access_key_id=XYZ
	heroku config:set aws_secret_access_key=XYZ

Step 12. Stage all the files in the demo app (git add .)

Step 13. Commit all the staged files (git commit -m "Initial commit")

Step 14. Launch the app (git push heroku master)

Step 15. Run bash on Heroku (heroku run bash)

Step 16. Run psiTurk from the Heroku bash prompt (psiturk)

Step 17. Create the HIT and answer the questions it asks (hit create), saying yes (y) when it asks if you're using an external process.

Step 18. Go to the sandbox and try out your HIT.
```

**Comment by braingineer** [comment]
Hi @suchow,

Thanks for your work! 

So to combine your and @deargle's points: 
- heroku is already SSL enabled, 
- if people aren't using the main ad server, they can deploy HITs that allow for repeat workers

So, then my question is: can Heroku support the custom ad server required to allow for repeat workers? Also, can the ad server be at the same location the experiment is hosted, e.g. can they be on the same Heroku deployment? 

Now that primary deadlines have passed, I'm starting to push on this a bit more.  

@suchow, your version of psiturk is heroku ready?  What's the difference between it and the main branch?    Also, would it be compatible with an approach that used [the one click deployment buttons](https://devcenter.heroku.com/articles/heroku-button)?  

Best,
Brian

**Comment by deargle** [comment]
I can answer these.

> if people aren't using the main ad server, they can deploy HITs that allow for repeat workers

Not quite, I haven't merged it yet. But I can.

> So, then my question is: can Heroku support the custom ad server required to allow for repeat workers? 

Yes, Heroku can serve the ad. There's not actually a custom ad server if you're not using the psiturk ad server. You just have to have regular-old https enabled for your study. If you can run your study in debug mode with https, then you can host your own ad. 

I'm guessing here, but Heroku likely has a/several https-enabled web server(s) running in front of all customers' stuff, and those web servers communicate with your individual app server via http. That's fine for mturk's requirements.

> Also, can the ad server be at the same location the experiment is hosted, e.g. can they be on the same Heroku deployment?

Yup you can host your own ad in the same location as your experiment.

As an aside, I recommend putting a reverse proxy server like nginx in front of psiturk for performance improvements, but that's not strictly necessary. And I don't have experience doing that with Heroku.

> @suchow, your version of psiturk is heroku ready? What's the difference between it and the main branch? Also, would it be compatible with an approach that used the one click deployment buttons?

I looked through and he adds code for reading in several environment variables for things that would normally be read from other files, such as .psiturkconfig. There's also some hacking during the ad creation process for if you're using the psiturk ad server, but I just pushed similar functionality to psiTurk proper called 'adserver_revproxy' which can do the same thing. So the difference will be with reading in via env variables.

> Also, would it be compatible with an approach that used the one click deployment buttons?

Not sure about this one.

**Comment by braingineer** [comment]
Thanks @deargle!  

> You just have to have regular-old https enabled for your study.

Aaah. So you're saying the only thing the ad server was allowing for was to let participants see the ad.html, and if you're serving the experiment behind an https connection, then they don't need the redirect? 

> I recommend putting a reverse proxy server like nginx in front of psiturk for performance improvements

That's a good idea. I'll check into that.  I've used things like that before for hiding jupyter notebook servers. I'm also not sure re: heroku, but I'm sure the answer exists somewhere on the internet. 

> So the difference will be with reading in via env variables.

Ah ok. So there isn't any underlying codebase changes to allow for psiturk to be deployed to heroku, other than the env variables vs psiturkconfig stuff.  

> one click deployment buttons

poking around quickly before a meeting and I found [this example](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api#post-deployment-scripts) of a post-deployment script.  Basically, I think it does mean it can deploy easily, as long as the repo is in a ready-set-go kind of status.

**Comment by deargle** [comment]
> So you're saying the only thing the ad server was allowing for was to let participants see the ad.html, and if you're serving the experiment behind an https connection, then they don't need the redirect?

That's correct.

BTW, allow_repeats (#214) is now merged into master. Still doesn't work on the psiTurk ad server though.

**Comment by gureckis** [comment]
Going off memory here but I think what the Ad server does is contact your psiTurk process and ask if the worker has completed the task before.  If you say yes, it will block them.  If you say no it will not.  So I think one could change the way psiTurk client works to not block repeats without touching ad server.  (I could be wrong... happy to look more deeply at it).

**Comment by deargle** [comment]
Hmm interesting. The code in question is right [here](https://github.com/NYUCCL/ad-psiturk-org/blob/0f98609a4037867491e71876bfba585a0862954d/app/__init__.py#L203) (socially acceptable to link a private repo in a public comment?)

**Comment by deargle** [comment]
Hacking the response status would lose the ability to filter out early quitters, but if that's an acceptable trade-off, yeah it could be done.

**Comment by gureckis** [comment]
Here's he other hint.... to decide to show the ad or an error message the ad server accesses "check_worker_status" route.  this returns the status in the database.  I think if you turn on "allow repeats" you could simply return a status that would be allowed. https://github.com/NYUCCL/psiTurk/blob/d00b5718c4a39277578d34e1b1c145cda606d84a/psiturk/experiment.py#L18

**Comment by deargle** [comment]
Oh you're right, no trade-off required.

**Comment by gureckis** [comment]
it would be interesting to force the status to NOT_ACCEPTED or ALLOCATED and see what happens on the ad server.  a more clean way would be to pass "allow repeats" to the ad server when you create the ad and then i can add some code to ignore the deny_already_completed_hit code for those ads.  this is actually the way the sandbox ad server works (it lets you repeat with same worker info).

**Comment by deargle** [comment]
It's easier on the local end to pass you 'allow repeats' during ad creation. I can do that right now... brb

**Comment by deargle** [comment]
do you want `allow_repeats` passed as an int?

**Comment by gureckis** [comment]
however is_sandbox is provided

**Comment by deargle** [comment]
Right, it's as an int.

**Comment by deargle** [comment]
I'm ready to test, but it's throwing an error until the ad server knows what to do with the passed `allow_repeats`, so let me know when.

**Comment by gureckis** [comment]
ok, i'm hacking on it now but it won't be a quick as you.  tonight or tomorrow.

**Comment by deargle** [comment]
No worries, I pushed to a [branch](https://github.com/NYUCCL/psiTurk/tree/allow-repeats-to-adserver).

**Comment by gureckis** [comment]
moving the part of this discussion about repeats to Issue #90

**Comment by Yuan-Meng** [comment]
@suchow Sorry to bother you with a silly question, Step 1-15 works perfectly fine for me, but when I entered `psiturk` in the Heroku bash prompt, the following error occurred:

`Traceback (most recent call last):
  File "/app/.heroku/python/bin/psiturk", line 11, in <module>
    load_entry_point('PsiTurk', 'console_scripts', 'psiturk')()
  File "/app/.heroku/src/psiturk/psiturk/command_line.py", line 15, in process
    launch_shell()
  File "/app/.heroku/src/psiturk/psiturk/command_line.py", line 101, in launch_shell
    import psiturk.psiturk_shell as ps
  File "/app/.heroku/src/psiturk/psiturk/psiturk_shell.py", line 31, in <module>
    from db import db_session, init_db
  File "/app/.heroku/src/psiturk/psiturk/db.py", line 27, in <module>
    engine = create_engine(DATABASE, echo=False, pool_recycle=3600) 
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 332, in create_engine
    return strategy.create(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 48, in create
    u = url.make_url(name_or_url)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 164, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 209, in _parse_rfc1738_args
    return URL(name, **components)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 59, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''`

I didn't change anything anywhere. Not sure why this would be the case. Thanks!

**Comment by deargle** [comment]
Show the config.txt that you pushed?

**Comment by deargle** [comment]
Thanks for your work, @suchow. I just set up psiturk proper to work with heroku following the pattern of your fork. Env vars for what would normally go in `.psiturkconfig` now are respected in `psiturk_config.py`, so `psiturk_shell.py` didn't have to be altered except for the improved logging bit.

Changes from your instructions: 
* one new env var (ON_HEROKU)
* one new config.txt setting (`adserver_revproxy_host` -- replaces the HOST env var step)
* hit can be created without needing to run bash on the server (no need to run `hit run bash`)

This is compatible with the `use_psiturk_ad_server=false` functionality.

I've copied your instructions below, with edits.

1. Create a Heroku account

2. Install the Heroku toolbelt (https://toolbelt.heroku.com/)

3. Install psiTurk (install from github until >v2.2.0 is released)

4. Create a copy of the demo app (`psiturk-setup-example`).

5. Initialize a Git repository inside the demo app (`git init`)

6. Create a new app using the Heroku toolbelt (`heroku create`)

7. Add a Postgres database to the Heroku app (`heroku addons:create heroku-postgresql`)

8. Get the URL of the Postgres database that you have just created (`heroku config:get DATABASE_URL`)

9. In the demo app, you should see a file `config.txt`. Replace the `database_url` (should start with postgresql://) with the URL that you retrieved in Step 8.

10. Also in config.txt, set `adserver_revproxy_host` to your heroku domain name. Run `heroku domains` to see your domain name.

11. Run the following command to tell your code that it is running on Heroku: 
`heroku config:set ON_HEROKU=true.`

13. Set environment variables for your psiTurk and MTurk, replacing XYZ with your access and secret keys:

```
    heroku config:set psiturk_access_key_id=XYZ
    heroku config:set psiturk_secret_access_id=XYZ
    heroku config:set aws_access_key_id=XYZ
    heroku config:set aws_secret_access_key=XYZ
```

14. Stage all the files in the demo app (`git add .`)

15. Commit all the staged files (`git commit -m "Initial commit"`)

16. Launch the app (`git push heroku master`)

17. Run psiTurk (`psiturk`)

18. Create the HIT and answer the questions it asks (hit create), saying yes (y) when it asks if you're using an external process.

19. Go to the sandbox and try out your HIT.

**Comment by braingineer** [comment]
Awesome!! Thanks for the ping!

**Comment by braingineer** [comment]
Hey @deargle,

running into some issues with your directions. I have a repo [here](https://github.com/braingineer/select). 

- it turns out heroku wants more information about that app. before pushing, you need to do:
  `heroku buildpacks:set heroku/python`
  and have a `requirements.txt`. 
- the error that @Yuan-Meng got was related to a formatting issue with the `revproxy_url` in `psiturk_shell.py`.  the fix is:
```
revproxy_url = "http://{}:{}/ad".format(self.config.get('Server Parameters', 
                                                        'adserver_revproxy_host'),
                                        port)
``` 

or, you could just wrap `port` in an `str` cast (`str(port)`).  

It might be faster if you push that in, mostly because I think it's in a couple of places.  in the meantime, the `requirements.txt` has a branch of psiturk that only differs on that one thing. 


So, those were mostly straight forward to work through. there is one that I'm just not sure about. it has to do with the heroku port and the web server.  (also, correct me if I'm wrong, but config.txt needs to be pointing to 0.0.0.0, right?).  Essentially, i can create the debug link, but it doesn't work. it says the server is running, but I can't connect.  I'm not entirely sure if it's b/c it's actually not running, or if it's b/c heroku is blocking it somehow. or, if it's not using the right port somehow. I guess that last one because when you do the `debug -p`, it prints out a link with port 80.  Not sure if it should be that way.

**Comment by braingineer** [comment]
to be more exact about that `revproxy_url` thing, here's a diff: https://github.com/NYUCCL/psiTurk/compare/master...braingineer:herokusafe?expand=1

**Comment by Yuan-Meng** [comment]
@deargle Below is what's in my config.txt
`[HIT Configuration]
title = Stroop task
description = Judge the color of a series of words.
amt_keywords = Perception, Psychology
lifetime = 24
us_only = true
approve_requirement = 95
contact_email_on_error = youremail@gmail.com
ad_group = Default psiTurk Stroop Example
psiturk_keywords = stroop
organization_name = New Great University
browser_exclude_rule = MSIE, mobile, tablet

[Database Parameters]
database_url = postgresql://postgres://bhqhvamgxbalfz:d7064a00d31354d67d2753fe1d4ee10f97cdfd1f2bb5536dc121e620d591abae@ec2-23-21-220-23.compute-1.amazonaws.com:5432/d15lvfpnghnjkh
table_name = turkdemo

[Server Parameters]
host = 0.0.0.0
port = 5000
cutoff_time = 30
logfile = server.log
loglevel = 2
debug = true
login_username = examplename
login_pw = examplepassword
threads = 1
secret_key = 'this is my secret key which is hard to guess, i should change this'
#certfile = <path_to.crt> 
#keyfile = <path_to.key>

[Task Parameters]
experiment_code_version = 1.0
num_conds = 1
num_counters = 1

[Shell Parameters]
launch_in_sandbox_mode = true

# If you are not using the psiturk ad server, set `use_psiturk_ad_server` to `false` and point `ad_location` to your proxy server <host> and <port>. Format the ad_location like this:
#
#   https://<host>:<port>/ad 

use_psiturk_ad_server = true
ad_location = false
`

**Comment by deargle** [comment]
Actually @yuan-meng's port error was related to sqlalchemy, according to the stack trace. It's because your database_url setting in your config.txt is messed up.

And @braingineer I forgot to make something clear -- my instructions assume that you do in fact start from `psiturk-setup-example`. There are three new files that are copied into the default example that heroku needs -- `requirements.txt`, `Procfile`, and `herokuapp.py`. And yes, you need to change `host` to 0.0.0.0 in config.txt.

And @suchow changed `threads` from `auto` to 1 in his code. I tested with that change too. Probably heroku will explode if more threads are attempted. Haven't tried yet. I'll go back and update the instructions in my first post.

> So, those were mostly straight forward to work through. there is one that I'm just not sure about. it has to do with the heroku port and the web server. (also, correct me if I'm wrong, but config.txt needs to be pointing to 0.0.0.0, right?). Essentially, i can create the debug link, but it doesn't work. it says the server is running, but I can't connect. I'm not entirely sure if it's b/c it's actually not running, or if it's b/c heroku is blocking it somehow. or, if it's not using the right port somehow. I guess that last one because when you do the debug -p, it prints out a link with port 80. Not sure if it should be that way.

Once you have Procfile in place, it should actually launch the server and you should be able to connect. When you deploy to heroku, it executes Procfile which execute herokuapp.py which directly launches the psiturk server, bound to whatever port heroku wants it to. Then to debug, you visit <your.heroku.domain> on plain 'ol port 80, which heroku redirects to the automagically-launched psiturk server, again, bound on whatever port it gave it. `port` in config.txt is ignored on the server.

**Comment by braingineer** [comment]
@deargle hmm. I might have run the `psiturk-setup-example` before I re-pulled the branch to get the newer updates because my repo was initialized with it just earlier this evening. I'll be sure to redo that then! 

re: everything else.
gotcha! thanks. will report if other issues. thanks!

**Comment by deargle** [comment]
@braingineer, were you experiencing an error with the port casting independent of @Yuan-Meng?

**Comment by deargle** [comment]
Sorry, silly question, I see now. I just couldn't imagine why my tests didn't catch that. I suppose I've always had `adserver_revproxy_port` set, so I never hit that casting issue. Thanks for the report.

**Comment by Yuan-Meng** [comment]
@braingineer I'm curious if you're using the custom version of psiTurk created by @suchow or the default version. I asked this because in the custom version, there's no `revproxy_url` in `psiturk_shell.py`.

**Comment by deargle** [comment]
He's using psiturk proper, with the code I just pushed earlier today.

**Comment by Yuan-Meng** [comment]
@deargle Ah, thank you! 

After dropping `postgresql://`, I'm finally able to launch psiTurk shell. However, (someone may have mentioned this) it seems I can't open the debug link that I was given. Also, I created a HIT and the `https://sandbox.ad.psiturk.org/view/gqUTR6xBdXNFTtzoBgSt6f?assignmentId=debugQDN486&hitId=debugAYHDZZ&workerId=debug27EHFJ` led me to "Error: 1018 (Description: The requested HIT is not registered with the psiTurk ad server.)"

**Comment by deargle** [comment]
> it seems I can't open the debug link that I was given

Need more information. Did you pull from master within the last hour?

> "Error: 1018 (Description: The requested HIT is not registered with the
psiTurk ad server.)"

In this case, that's an inaccurate error message description. The problem
is that your psiturk credentials aren't set correctly on heroku. Check to
make sure that you set the env vars correctly in this step:

```
heroku config:set psiturk_access_key_id=XYZ
heroku config:set psiturk_secret_access_id=XYZ
```

Make sure you didn't put quotes around your values. Maybe share the results
of `heroku config`, trimming the middle of the keys, just so we see that
you didn't typo something.

**Comment by Yuan-Meng** [comment]
@deargle 
1. About the debug link: 

> Did you pull from master within the last hour?

Yes. In fact, I went through all required steps within a few minutes.

2. About the 1018 error:

> psiturk credentials aren't set correctly on heroku...
Below is what I typed in terminal when setting env vars:
`heroku config:set psiturk_access_key_id=myKey`
`heroku config:set psiturk_secret_access_id=myKey`
`heroku config:set aws_access_key_id=myKey`
`heroku config:set aws_secret_access_key=myKey`
I doubled checked if I entered the correct keys and I did. 

I'll try the psiTurk proper version to see how that goes... Thanks!

**Comment by deargle** [comment]
@Yuan-Meng @braingineer I just released a new version of psiturk to pip (v2.2.1) so that when heroku installs via `requirements.txt`, it actually works. The version of `requirements.txt` that I bundled with the example app references an unpinned `PsiTurk`, so it should pick up the version bump. Heroku needs the updates in 2.2.1. Sorry about that, forgot that not bumping would lead to issues -- my version of requirements.txt that I was testing against was installing off of github master, not pip. 

So if you were having troubles, try [rebuilding your heroku app](http://stackoverflow.com/questions/9713183/recompile-heroku-slug-without-push-or-config-change).

**Comment by Yuan-Meng** [comment]
@deargle Thanks for the new version! 

It's strange that I'm keeping getting Error #1018 (The requested HIT is not registered with the psiTurk ad server.)--I even regenerated my psiTurk keys and AMS keys and checked many times that they are indeed correct.

I also don't think there were typos when I set env vars: (digits in the middle are replaced with ...)
`heroku config:set psiturk_access_key_id=vGB...jz3`
`heroku config:set psiturk_secret_access_id=5EJ...ghW`
`heroku config:set aws_access_key_id=AKI...Y6A`
`heroku config:set aws_secret_access_key=xql...Glv`

Are there any other possible reasons for Error #1018?

**Comment by deargle** [comment]
Here's a quick way to set the four heroku configs:

``` Python
from psiturk.psiturk_config import PsiturkConfig
import subprocess

CONFIG = PsiturkConfig()
CONFIG.load_config()

sections = ['psiTurk Access','AWS Access']
for section in sections:
    for item in CONFIG.items(section):
        #print 'heroku config:set ' + '='.join(item)
        subprocess.call('heroku config:set ' + '='.join(item), shell=True)
```

**Comment by fredcallaway** [comment]
Following @deargle's instructions, I got an error pushing to heroku
```
remote: -----> Installing requirements with pip
remote:        Collecting PsiTurk (from -r /tmp/build_234e4f44275e3c599ef45def57fcb8ed/requirements.txt (line 1))
remote:          Downloading PsiTurk-2.2.3.tar.gz (3.4MB)
remote:        Collecting psycopg2==2.6.2 (from -r /tmp/build_234e4f44275e3c599ef45def57fcb8ed/requirements.txt (line 2))
remote:          Downloading psycopg2-2.6.2.tar.gz (376kB)
remote:            Complete output from command python setup.py egg_info:
remote:            running egg_info
remote:            creating pip-egg-info/psycopg2.egg-info
remote:            writing pip-egg-info/psycopg2.egg-info/PKG-INFO
remote:            writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
remote:            writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
remote:            writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
remote:            Error: could not determine PostgreSQL version from '10.1'
remote:
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GI99GZ/psycopg2/
remote:  !     Push rejected, failed to compile Python app.
```

which I was able to solve by removing the `==2.6.2` from requirements.txt, so it now reads
```
PsiTurk
psycopg2
```

**Comment by deargle** [comment]
@fredcallaway odd that it works for me still, but yeah https://github.com/psycopg/psycopg2/issues/594 says 2.7.1 works.

**Comment by fredcallaway** [comment]
Haha looks like you beat me to the pull request ;)

**Comment by deargle** [comment]
I'm ultra fast when I can just use the github gui to make changes ;-)

**Comment by Speldosa** [comment]
I've created a pull request (#311) where I've written up some of the information on how to use `psiTurk` with `Heroku`. I'm thinking about maybe looking into creating a Python script that sets up everything for you. However, here there seems to be some discussion regarding automatically setting up your own ad server on Heroku as well, something that I'm not familiar with how you would do.

If somebody more experienced would like to lead the way, I could help out creating the more mundane parts of the script. Otherwise, I might just go ahead and just create what I can handle right now.

**Comment by deargle** [comment]
It's not "set up your own ad server" -- rather, it's "host your own ad
using the same server that runs your psiturk experiment instead of relying
on the psiturk ad server". It's as simple as telling mturk that the
location of your ad is `https://<your heroku domain>/pub`. /pub is a
synonym for /ad, where /pub is used instead to avoid ad blockers.

To switch psiturk to not use the psiturk ad server, you just set the last
two config options to `false` and the `route to your heroku domain /pub`
respectively.

**Comment by Speldosa** [comment]
Oh, I thought the process was more complicated. Well, I'll try that out and add it to the documentation. I should be able to write the setup script myself then.

**Comment by abardon** [comment]
When using Heroku, no data seems to be saved to my postgres database. When just hosting locally, data is recorded properly to the local participants.db. When I follow the steps to setup heroku and then run a trial, the download_datafiles command no longer finds any data in my postgres database. Any suggestions?

**Comment by deargle** [comment]
Likely you did not set ON HEROKU env var, so it is not using the postgres
db, and it is saving to a local, inaccessible sqlite db.

**Comment by abardon** [comment]
Is that the "heroku config:set ON_HEROKU=true" command? I ran that when setting it up, but still can't use download_datafiles.

**Comment by deargle** [comment]
I haven't used the `download_datafiles` command in... ever. Why do you think that no data is being saved? If you log into the db (`heroku psql`), is there data there? And have you updated your `database_url` in your local `config.txt` to point to the postgresql db? If you haven't, then I don't think that `download_datafiles` would find anything, because it wouldn't be looking in the right place.

**Comment by abardon** [comment]
I did update config.txt. The datastring in the postgresql db is just a very long unreadable string of letters and numbers, unlike the one that saved in my participants.db before which was a very long string of all the data in the format that I specified. I'm not sure if it has been written correctly?

**Comment by deargle** [comment]
It's long because it includes your heroku-supplied username:password. sqlite doesn't have authentication, so therefore shorter.

Have you logged in to check yet?

**Comment by abardon** [comment]
I'm looking at the database in postico, and the datastring doesn't have the data that i wrote with psiTurk.recordTrialData() anywhere in it. Is this an ok way to look at it?

**Comment by tianweigong** [comment]
> I'm looking at the database in postico, and the datastring doesn't have the data that i wrote with psiTurk.recordTrialData() anywhere in it. Is this an ok way to look at it?

I have a similar problem here. I used the stroop example. All procedure in sandbox went right but finally there was no data in the heroku database.( If I run download_datafiles, there would be "('No trial data found in record:', Subject(uniqueid|A3I6Y8407JIPA1:354P56DE9L689F2BRQ3YPQSRHSSS7B, condition|0, status|4, codeversion|1.0)) -- subject id ✔ data ✘.

**Comment by deargle** [comment]
Going forward, let's create new issues for heroku-related problems. I'm going to look at the datastring issue rn.
