### ISSUE TITLE
server log fails with OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mvdoc** [NYUCCL/psiTurk#262]
I haven't managed to make `server log` work successfully in the psiturk shell. Here's the error I get

```
[psiTurk server:off mode:sdbx #HITs:0]$ server on
Experiment server launching...
Now serving on http://0.0.0.0:22362
[psiTurk server:on mode:sdbx #HITs:0]$
[psiTurk server:on mode:sdbx #HITs:0]$ server log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 782, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 865, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 91, in helper_fn
    return func(self, opt)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 454, in do_server
    self.server_log()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 252, in server_log
    subprocess.Popen(args, close_fds=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[Errno 2] No such file or directory
```

Here's the server configuration from `config.txt`

```
[Server Parameters]
host = 0.0.0.0
port = 22362
cutoff_time = 30
logfile = test.log
loglevel = 2
debug = false
threads = auto
```

and if you want to reproduce it, I'm running psiturk + mysql within a Docker container, which you can find here: https://github.com/mvdoc/psiturk-docker

**Comment by mvdoc** [comment]
Inspecting https://github.com/NYUCCL/psiTurk/blob/master/psiturk/psiturk_shell.py#L251 I realize that server log requires xterm, which I'm not running in the Docker container to avoid installing Xserver.

**Comment by deargle** [comment]
As an alternative, you can always manually inspect server.log in the same
dir as your config.txt
