### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by PatrickLaflamme** [NYUCCL/psiTurk#274]
When I try to open psiturk, I get the following error:

```
***********************************************************
WARNING
Unable to establish connection to AWS RDS (Amazon relational database services).
See relevant psiturk docs here:
	http://psiturk.readthedocs.io/en/latest/configure_databases.html#obtaining-a-low-cost-or-free-mysql-database-on-amazon-s-web-services-cloud
***********************************************************
Traceback (most recent call last):
  File "/home/smilera4/public_html/vMRT/venv/bin/psiturk", line 11, in <module>
    sys.exit(process())
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/command_line.py", line 15, in process
    launch_shell()
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/command_line.py", line 111, in launch_shell
    ps.run(cabinmode=args.cabinmode)
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1948, in run
    config.getboolean('Shell Parameters', 'launch_in_sandbox_mode'), quiet=quiet)
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 550, in __init__
    PsiturkShell.__init__(self, config, server)
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 124, in __init__
    self.intro = self.get_intro_prompt()
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 605, in get_intro_prompt
    server_msg = self.web_services.get_system_status()
  File "/home/smilera4/public_html/vMRT/venv/lib/python2.7/site-packages/psiturk/psiturk_org_services.py", line 71, in get_system_status
    response = urllib2.urlopen(api_server_status_link, timeout=1)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/smilera4/public_html/vMRT/Python2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

```

I can't figure out how to solve this, but my understanding is that the error is thrown when trying to connect with the psiturk website.

**Comment by gureckis** [comment]
It is trying to open this link: https://api.psiturk.org/status_msg?version=2.1.1 
if it loads from your browser it suggests you have some problem with a library psiturk depends on like urlopen.  that link works for me so its not a system outage.

**Comment by PatrickLaflamme** [comment]
You were correct. Reinstalled python from source and it worked.
