### ISSUE TITLE
postgres connection problem

### ISSUE THREAD

**Issue by doncwilliam** [NYUCCL/psiTurk#324]
Hello all,

I am trying to substitue sqlite database using postgresql using psiturk-example from the quick start. I tested that the psiturk-example is working correctly. I can also connect to the postgresql database from my computer. 

I then modified config.txt by changing database_url to be 
`database_url = postgresql://user:password@localhost:5432`
I also tried 
`database_url = postgresql://user:password@localhost:5432/turkdemo`

I pip installed psycopg2.

When I launch psiturk, it is fine in server off mode. However, if I turn on server, I get the following error:

```
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from re
lease 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psyc
opg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/user/py27/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 99, in <module>
    launch()
  File "/home/user/py27/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 96, in launch
    ExperimentServer().run()
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 206, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 302, in halt
    self.stop()
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 347, in stop
    time.sleep(0.1)
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/home/user/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/user/py27/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

```
Then I pip uninstalled psycopg2, and pip installed psycopg2-binary.

When I launch psiturk, it is fine in server off mode. However, if I turn on server, I get the following error:

```
Traceback (most recent call last):
  File "/home/chris/py27/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 99, in <module>
    launch()
  File "/home/chris/py27/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 96, in launch
    ExperimentServer().run()
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 206, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 302, in halt
    self.stop()
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 347, in stop
    time.sleep(0.1)
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/home/chris/py27/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

```

Does anyone know how to make psiturk work with postgres? I tried it with different database_url as indicated above, but they all behave the same way.

Thanks a lot!
Don

**Comment by deargle** [comment]
HOW DID YOU RESOLVE

**Comment by hyiltiz** [comment]
I am trying to strictly follow psiTurk's documentation on switching from sqlite3 to mysql on macOS 10.14.2 with Homebrew. Once everything is set up, when I do `server on`, I get this message, similar to the one above:
```
Experiment server launching...
Now serving on http://127.0.0.1:22362
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 99, in <module>
    launch()
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment_server.py", line 96, in launch
    ExperimentServer().run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 206, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 302, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 347, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```
Everything works fine with `sqlite3`, or if I directly connect to my database via `mysql -u my_user -p` then do `CONNECT my_database;`.

**Comment by deargle** [comment]
Check server.log for the error that is crashing gunicorn.

**Comment by hyiltiz** [comment]
It is about `tx_isolation` thrown by sqalchemy. I am wondering if this is some version mismatch between the whole stack (mysql/mariadb, sqalchemy, pysql/mysql-python, gunicorn, psiturk). I also tried building from source from `master`, `dev`, last merge by Todd but they all threw errors (mostly the above above about `gunicorn`) but the latest `master` branch throws an error about parameter dispatching. I am also attaching the full `server.log` file for all my struggle today. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/PsiTurk-2.2.3-py2.7.egg/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/site-packages/PsiTurk-2.2.3-py2.7.egg/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/usr/local/lib/python2.7/site-packages/PsiTurk-2.2.3-py2.7.egg/psiturk/db.py", line 39, in init_db
    Base.metadata.create_all(bind=engine)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1471, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
    self.pool.connect(),
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 272, in connect
    return _ConnectionFairy(self).checkout()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 431, in __init__
    rec = self._connection_record = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _do_get
    con = self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 225, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 322, in __init__
    exec_once(self.connection, self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/event.py", line 392, in exec_once
    self(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/event.py", line 409, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1049, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 168, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2139, in initialize
    default.DefaultDialect.initialize(self, connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 181, in initialize
    self.get_isolation_level(connection.connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2014, in get_isolation_level
    cursor.execute('SELECT @@tx_isolation')
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1193, u"Unknown system variable 'tx_isolation'")
```

[server.log](https://github.com/NYUCCL/psiTurk/files/2714306/server.log)

**Comment by hyiltiz** [comment]
This post [1] says it was due to broken backward compatibilities in mysql 8.0 and that a later sqalchemy version is needed. psiTurk currently asks specifically for 0.8.3 while the latest in PyPi is 1.2.15.

[1] https://stackoverflow.com/questions/50156520/cannot-connect-to-a-local-mysql-db-with-sqlalchemy-on-windows-machine

**Comment by hyiltiz** [comment]
Ok I fixed it by updating the dependencies. Sending a pull request.
