### ISSUE TITLE
bug when trying to pay workers

### ISSUE THREAD

**Issue by andrebeu** [NYUCCL/psiTurk#347]
hello,

I've been running experiments with psiturk for a while now, and everything was working, until oneday I tried to approve workers and got the following error:

```
[psiTurk server:on mode:live #HITs:1]$ worker approve --hit 3XJOUITW8UNDEDVE9TMS162YEC2QTT
Approving submissions for HITs 3XJOUITW8UNDEDVE9TMS162YEC2QTT for the current study
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/cmd2.py", line 782, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/cmd2.py", line 865, in onecmd
    stop = func(statement)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 57, in helper_fn
    return func(self, opt)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1038, in do_worker
    self.worker_approve(arg['--all'], arg['<hit_id>'], arg['<assignment_id>'], arg['--all-studies'], arg['--force'])
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 395, in worker_approve
    workers = self.amt_services_wrapper.get_workers("Submitted", chosen_hits, assignment_ids, all_studies=all_studies)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/psiturk/amt_services_wrapper.py", line 133, in get_workers
    my_hitids = self._get_my_hitids()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/psiturk/amt_services_wrapper.py", line 290, in _get_my_hitids
    my_hitids = [part.hitid for part in Participant.query.distinct(Participant.hitid)]
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    fetch = cursor.fetchall()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1218, in fetchall
    e, None, None, self.cursor, self.context
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1213, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1163, in _fetchall_impl
    return self.cursor.fetchall()
OperationalError: (sqlite3.OperationalError) Could not decode to UTF-8 column 'CSWfall18_datastring' with text '{"condition":49,"counterbalance":0,"assignmentId":"31LVTDXBL86STLZ231E38PY88YZLRX","workerId":"AE2QWV0TZNJAN","hitId":"3XJOUITW8UND
(Background on this error at: http://sqlalche.me/e/e3q8)
(sqlite3.OperationalError) Could not decode to UTF-8 column 'CSWfall18_datastring' with text '{"condition":49,"counterbalance":0,"assignmentId":"31LVTDXBL86STLZ231E38PY88YZLRX","workerId":"AE2QWV0TZNJAN","hitId":"3XJOUITW8UND
(Background on this error at: http://sqlalche.me/e/e3q8)
```

I have no idea what's going on since this was literally from one day to the next. any help would be much appreciated!!

**Comment by deargle** [comment]
Try upgrading, https://groups.google.com/d/msg/psiturk/x8tcm0I2EPk/psqGsMzuDQAJ

**Comment by andrebeu** [comment]
just noticed I am currently using 2.2.4.
on github, it says the latest version is 2.2.3
would you suggest downgrading in that case?

**Comment by deargle** [comment]
No.

**Comment by andrebeu** [comment]
okay! anything else I can try at this moment?

**Comment by deargle** [comment]
Did you try upgrading to latest on master, following the link I shared earlier?

**Comment by andrebeu** [comment]
ah i see, you mean using the latest commit, and not the latest stable version.
I'll try that and report back!

**Comment by deargle** [comment]
Closing bc of inactivity
