### ISSUE TITLE
AMT SyntaxError

### ISSUE THREAD

**Issue by swj0418** [NYUCCL/psiTurk#373]
**Congratulations on supporting python3! I was looking forward to this. However, when trying to turn on psiTurk CLI, this error message pops up. I tried on Ubuntu 16 and 18.**

Traceback (most recent call last):
  File "/usr/local/bin/psiturk", line 11, in <module>
    load_entry_point('PsiTurk==2.3.2', 'console_scripts', 'psiturk')()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.3.2-py2.7.egg/psiturk/command_line.py", line 16, in process
    launch_shell()
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.3.2-py2.7.egg/psiturk/command_line.py", line 110, in launch_shell
    import psiturk.psiturk_shell as ps
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.3.2-py2.7.egg/psiturk/psiturk_shell.py", line 21, in <module>
    from psiturk.amt_services_wrapper import MTurkServicesWrapper
  File "/usr/local/lib/python2.7/dist-packages/PsiTurk-2.3.2-py2.7.egg/psiturk/amt_services_wrapper.py", line 765
    raise AmtServicesWrapperError('Error expiring hit {}'.format(hit_id)) from response.exception
                                                                             ^
SyntaxError: invalid syntax

**If there is any more information needed, please tell me. Thanks in advance!**

**Comment by deargle** [comment]
Use a virtualenv. And use psiturk 2.3.3

**Comment by swj0418** [comment]
I will try it thank you very much.
