### ISSUE TITLE
"TemplateNotFound" error for custom route 

### ISSUE THREAD

**Issue by tree-pi** [NYUCCL/psiTurk#399]
I'm writing a custom route to trigger a python function. I copied codes from [other examples](https://github.com/alexanderrich/exploration_consumption/tree/8c1ab6be5e3d7e7777d4653a3503a5095cbfd82e/experiment2) but it gives 500 error in the console and the server log is as follows:

```2020-02-04 15:57:49,127 Exception on /send_marker [GET]
Traceback (most recent call last):
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/zl1228/anaconda3/envs/vp3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: send_marker
```

Seems to me that flask is trying to find some templates but I don't have any html template to edit but instead just wanna run some python things. Any suggestion on how to resolve this error?

--------
Here's my custom.py excerpt:

```
custom_code = Blueprint('custom_code', __name__)
@custom_code.route('/send_marker',methods=['POST'])
def send_marker():
    from pylsl import StreamInfo, StreamOutlet

    # Create a new labstreaminglayer outlet
    outlet = StreamOutlet() # to broadcast out
    # send incoming data to LSL
    dicty = loads(request.args)
    message = dicty.get('message')
    event = message.get('event')
    timeStamp = message.get('time')
    outlet.push_sample([event,timeStamp])

    return make_response('marker is sent!',
                         200)
```

--------
Here's my js code:
```
$.ajax("send_marker",{
                      dataType: "json",
                      methods:["POST","GET"],
                      data: {time: timenow, event: 'start tutorial'},
                      success: function (data) {
                          console.log("marker sent");
                      }
                  });
```

Thanks a lot!

**Comment by deargle** [comment]
opening issues on psiturk is for bugs, but yours is fundamentally a nearly-pure jquery / flask question.

You are not using jQuery's ajax method correctly. It has no `methods` argument. Rather, it has `method`, and `type` which is an alias for `method`. Only specify one method, it makes no sense to send a request using both POST and GET. Your flask custom route only accepts `POST`, so do that:

```js
$.ajax("send_marker",{
                      dataType: "json",
                      method:"POST",
                      data: {time: timenow, event: 'start tutorial'},
                      success: function (data) {
                          console.log("marker sent");
                      }
                  });
```

The example you say you are copying from used `type`, which, again, is equivalent.

The error message is flask falling back on a default route for unrecognized/unregistered routes: https://github.com/NYUCCL/psiTurk/blob/993f114c060f9cb43e84da9a64a695bc03023025/psiturk/experiment.py#L782-L796

Since your ajax method is using GET method by default, and you have no custom route registered for `send_marker` using GET, it's falling back on attempting to load a `send_marker.html` template. DNE therefore error you saw.

**Comment by tree-pi** [comment]
I see. I confused the "methods" in flask with ajax. Great explanation! Thanks a lot!
