### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by yang-yangfeng** [NYUCCL/psiTurk#400]
I'm running into the following error when I try `psiturk -e "server on"` or even just `psiturk`.  Seems similar to issue #336, but I think it's a different issue since I already have certifi installed/seems like you guys made the necessary changes to the `requirements.txt` 

I've been running `psiturk v2.3.3` for months now and have never run into this issue. In fact, things were working fine yesterday. Problem came up on my macbook pro, MacOS 10.14.6 when I wanted to do local testing. Haven't tried on EC2 where I usually host real HITs.

```Traceback (most recent call last):
  File "/Users/yafeng/.pyenv/versions/2.7.16/bin/psiturk", line 11, in <module>
    load_entry_point('PsiTurk==2.3.3', 'console_scripts', 'psiturk')()
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/command_line.py", line 16, in process
    launch_shell()
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/command_line.py", line 123, in launch_shell
    ps.run(cabinmode=args.cabinmode, execute=execute, quiet=True)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1292, in run
    quiet=quiet)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 776, in __init__
    if not self.amt_services_wrapper:
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 760, in amt_services_wrapper
    config=self.config, web_services=self.web_services, sandbox=self.sandbox)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 752, in web_services
    self.config.get('psiTurk Access', 'psiturk_secret_access_id'))
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_org_services.py", line 47, in __init__
    if not self.check_credentials():
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/psiturk/psiturk_org_services.py", line 58, in check_credentials
    auth=(self.access_key, self.secret_key))
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yafeng/.pyenv/versions/2.7.16/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.psiturk.org', port=443): Max retries exceeded with url: /api/ad (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))```

**Comment by deargle** [comment]
Upgrade psiturk

**Comment by gureckis** [comment]
the SSL certificates for api.psiturk.org and ad.psiturk.org renewed today so it is possibly related to that.  try again in a few hours and see if its resolves, but agree latest psiturk is recommended usually.

**Comment by deargle** [comment]
Indeed, newer versions of psiturk dont ping api.psiturk.org on startup.

**Comment by yang-yangfeng** [comment]
Superstitious about changing anything about data collection - but upgrading did the trick and nothing seems to be broken yet. Thank you!
