### ISSUE TITLE
Server on not working after installation (failed with HaltServer)

### ISSUE THREAD

**Issue by fspinar** [NYUCCL/psiTurk#519]
Hi all,

I am trying to run the server on comment after installation, as instructed in the documentation (https://psiturk.readthedocs.io/en/latest/quickstart.html#step-1-install-psiturk)
Yet I get the following error :

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/faspinar/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/faspinar/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2021-06-25T09:31:27Z <Greenlet at 0x7f2fa5e626a0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f2fa60fc0d0>>(17, None)> failed with HaltServer

Any idea how to solve this ? I realized other people also experienced this and tried some suggestions I saw on the Web, but none worked so far. I installed psiturk 3.2.0and have python 2.7 3.8 3.9 . I am working on WSL2 , but don't know whether this effects anything in anyway.

Thanks all.

**Comment by deargle** [comment]
Check your server.log file for the error messages.

**Comment by fspinar** [comment]
Ok I checked and I got : 
self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available

Any suggestion for solving this ?

Thank you.

**Comment by deargle** [comment]
That's the _only entry_ in your server.log file?

**Comment by fspinar** [comment]
I tried many times and in the log file the same error is replicated... To be complete the full error is :

Traceback (most recent call last):
  File "/home/faspinar/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/faspinar/.local/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 160, in init_process
    self.patch()
  File "/home/faspinar/.local/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 61, in patch
    sockets.append(socket.socket(s.FAMILY, socket.SOCK_STREAM,
  File "/home/faspinar/.local/lib/python3.8/site-packages/gevent/_socket3.py", line 133, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available

Is this full version kind of better ? 

Thanks

**Comment by deargle** [comment]
Hmm try from a virtual environment, to rule out a missing package install.
I run psiturk from wsl 2 ubuntu 18 without incident.

**Comment by fspinar** [comment]
It is interesting but the error is simply gone when I switch to Ubuntu 18.04 (from 20.04) on WLS2. 
Thanks !
