### ISSUE TITLE
`MarkupSafe` removes deprecated `soft_unicode` in v2.1.0

### ISSUE THREAD

**Issue by jmuchovej** [NYUCCL/psiTurk#541]
https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

Error, if you need it: `ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/markupsafe/__init__.py)`

I can open/submit a PR in a few hours fixing this, just now right now. This will break any installations past 17 Feb 2022, so it seems rather high-priority.

**Comment by jacob-lee** [comment]
I don't see this package in psiturks's requirements. Is it a dependency of
Flask's perhaps? In that case, I'm not sure this is an issue that we can
address here...

**Comment by jmuchovej** [comment]
So, this _is_ coming from Flask. Here's the full traceback.
```python
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/psiturk", line 8, in <module>
    sys.exit(process())
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/psiturk/command_line.py", line 14, in process
    launch_shell()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/psiturk/command_line.py", line 94, in launch_shell
    import psiturk.psiturk_shell as ps
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/psiturk/psiturk_shell.py", line 17, in <module>
    from psiturk.amt_services_wrapper import MTurkServicesWrapper
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/psiturk/amt_services_wrapper.py", line 13, in <module>
    from .amt_services import MTurkServices
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/psiturk/amt_services.py", line 9, in <module>
    from flask import jsonify
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/markupsafe/__init__.py)
```

**Comment by deargle** [comment]
I'm seeing recommendations that we pin markupsafe to 2.0.1: https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1043965261

I didn't do a full `pip freeze` to make the requirements list, which I think had some benefit or other, but this soft_unicode thing is a downside.
